# --------------------------
# Uygulama Ayarları
# --------------------------
spring.application.name=ahir
server.port=8080

# --------------------------
# MySQL Veritabanı
# --------------------------
spring.datasource.url=jdbc:mysql://localhost:3306/ahir?useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=19071907
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# --------------------------
# JPA / Hibernate
# --------------------------
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect
spring.jpa.show-sql=true
spring.jpa.open-in-view=false